### PR TITLE
Updated readme information

### PR DESCRIPTION
**Pull request by FredrikBakken**
Previous readme information was outdated and with incorrect information (e.g. micropython was mentioned in this Lua specific example application).

### CODE REVIEW

**Review by gabrielmocanu — CHANGES_REQUESTED** [review]
I tested and all went well, but I would change the README a bit to be as general as possible for all applications.
So for this, I think it's better to have the same structures as in these PRs [1] [2] [3] also for lua.

@FredrikBakken  Can you do this? Thanks.

[1]: https://github.com/unikraft/app-nginx/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
[2]: https://github.com/unikraft/app-sqlite/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
[3]: https://github.com/unikraft/app-redis/pull/3/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by FredrikBakken** [comment]
Hi @gabrielmocanu! Sorry for the late reply. I have now updated the `readme.md` description by using the [`app-python3`](https://github.com/unikraft/app-python3) as inspiration. Please let me know if any further changes are needed.

**Review by gabrielmocanu — APPROVED** [review]
Thanks for the update @FredrikBakken !
Now all seems good to me.

Reviewed-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
